// biome-ignore-all lint: Testing CSG (not used)

import { useEffect, useMemo } from "react";
import { useTexture } from "@react-three/drei";
import * as THREE from "three";
import { Brush, Evaluator, SUBTRACTION } from "three-bvh-csg";

type RafterCSGProps = {
  length?: number;
  height?: number;
  depth?: number;
};

export default function RafterCSG({
  length = 2.0,
  height = 0.15,
  depth = 0.15,
  ...meshProps
}: RafterCSGProps & JSX.IntrinsicElements["mesh"]) {
  const texture = useTexture("/textures/uv_texture_color.webp");
  texture.wrapS = texture.wrapT = THREE.RepeatWrapping;
  texture.colorSpace = THREE.SRGBColorSpace;

  const { geometry, material } = useMemo(() => {
    // 1. Create main rafter body (simple box)
    const rafterGeo = new THREE.BoxGeometry(depth, height, length);
    const rafterBrush = new Brush(rafterGeo);
    rafterBrush.updateMatrixWorld();

    // 2. Create cutting box for "bird's mouth" notch
    const cutWidth = depth; // Full width of rafter
    const cutHeight = height * 0.4; // Cut 40% of the height
    const cutDepth = depth * 0.5; // Cut depth

    const cutGeo = new THREE.BoxGeometry(cutWidth, cutHeight, cutDepth);
    const cutBrush = new Brush(cutGeo);

    // Position the cut at the bottom, about 1/4 along the rafter length
    cutBrush.position.set(
      0, // Centered on width
      -height / 2 + cutHeight, // At the bottom
      -length / 4, // 1/4 along from center
    );
    cutBrush.updateMatrixWorld();

    // 3. Perform boolean subtraction
    const evaluator = new Evaluator();
    const resultBrush = evaluator.evaluate(rafterBrush, cutBrush, SUBTRACTION);

    // 4. Get the resulting geometry
    const resultGeo = resultBrush.geometry;
    resultGeo.computeVertexNormals();
    resultGeo.computeBoundingBox();
    resultGeo.computeBoundingSphere();

    // 5. The UVs are generated by CSG but won't be great
    // You can see what CSG does to them with your color UV texture
    console.log("CSG Result:", {
      vertices: resultGeo.attributes.position.count,
      hasUVs: !!resultGeo.attributes.uv,
      uvCount: resultGeo.attributes.uv?.count,
    });

    const mat = new THREE.MeshStandardMaterial({
      map: texture,
      side: THREE.DoubleSide, // To see inside the cut
    });

    return {
      geometry: resultGeo,
      material: mat,
    };
  }, [length, height, depth, texture]);

  useEffect(() => {
    return () => {
      geometry.dispose();
      if (material.map && material.map !== texture) {
        material.map.dispose();
      }
      material.dispose();
    };
  }, [geometry, material, texture]);

  return <mesh geometry={geometry} material={material} {...meshProps} />;
}
